# Generated by Django 3.2.7 on 2021-10-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_nombre', models.CharField(max_length=30, unique=True)),
                ('e_estado', models.BooleanField(default=True)),
                ('e_capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('b_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('b_condicion', models.BooleanField()),
                ('b_en_prestamo', models.IntegerField()),
                ('b_en_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contiene', to='MoveAndFlowApp.estacion')),
            ],
        ),
    ]
