# Generated by Django 3.2.7 on 2021-10-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveAndFlowApp', '0004_alter_bicicleta_b_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='e_capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
