# Generated by Django 3.2.7 on 2021-10-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveAndFlowApp', '0005_alter_estacion_e_capacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='b_en_prestamo',
            field=models.IntegerField(null=True),
        ),
    ]
