# Generated by Django 3.2.7 on 2021-10-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveAndFlowApp', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='u_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='u_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='Admin', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
