# Generated by Django 3.2.7 on 2021-10-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoveAndFlowApp', '0008_auto_20211014_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_inicio', models.DateTimeField(auto_now_add=True)),
                ('p_fin', models.DateTimeField()),
                ('p_destino', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to='MoveAndFlowApp.estacion')),
                ('p_origen', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='presta', to='MoveAndFlowApp.estacion')),
            ],
        ),
    ]
