# Generated by Django 3.2.7 on 2021-10-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveAndFlowApp', '0009_auto_20211031_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='b_en_prestamo',
            field=models.BooleanField(default=False),
        ),
    ]
