# Generated by Django 3.2.7 on 2021-10-30 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MoveAndFlowApp', '0009_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='p_fin',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='active_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestamo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
