# Generated by Django 3.2.7 on 2021-10-30 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MoveAndFlowApp', '0010_auto_20211030_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='is_active',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='p_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
