# Generated by Django 3.2.7 on 2021-10-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoveAndFlowApp', '0011_alter_prestamo_p_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='p_fin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
